.devcontainer/Containerfile, .devcontainer/devcontainer.json, .github/dependabot.yml
Add VS Code devcontainer configuration files to make local development and testing easier on non-Linux platforms.
=> Add devcontainer.json configuration

jumpstarter/cli/client.py, jumpstarter/config/client.py, jumpstarter/config/user.py, tests/test_client_config.py, tests/test_user_config.py
Improve config code style to prevent confusion with different arguments.
=> Force kw_only for all config classes

jumpstarter/cli/client.py, jumpstarter/config/__init__.py, jumpstarter/config/client.py, jumpstarter/config/common.py, jumpstarter/config/user.py, tests/test_client_config.py, tests/test_user_config.py
We also need to think about future config version updates.
Proposal:
Support loading old versions, only support writing latest version. When saving old versions, transparently upgrade them to the latest version.
=> Reimplement ClientConfig with pydantic

jumpstarter/common/streams.py, jumpstarter/drivers/base.py, jumpstarter/drivers/decorators.py, jumpstarter/exporter/session.py
The continuation of explicit stream cancellation work, now server streams (driver side of the stream) can also be cancelled. This also fully mitigates the pitfall described in https://anyio.readthedocs.io/en/stable/cancellation.html#avoiding-cancel-scope-stack-corruption
=> Make server stream a context manager, implement keepalive

contrib/can/pyproject.toml, contrib/dutlink/pyproject.toml, contrib/raspberrypi/pyproject.toml, contrib/ustreamer/pyproject.toml, pyproject.toml, uv.lock
This change uses hatch-vcs to dynamically inject the wheel versions based on the git tags/commit/etc.
Related-To: https://github.com/jumpstarter-dev/jumpstarter/issues/87
=> Use dynamic versioning from git in python wheels

jumpstarter/drivers/storage/client.py, jumpstarter/drivers/storage/driver_test.py
Fixes https://github.com/jumpstarter-dev/jumpstarter/issues/113
=> Make StorageMuxClient.write_local_file accept relative path

jumpstarter/cli/client.py, jumpstarter/client/lease.py, jumpstarter/config/client.py, jumpstarter/config/exporter_test.py
This is for tekton integration.
=> Allow specifying existing lease name in jmp client shell

jumpstarter/common/grpc.py, jumpstarter/common/streams.py, jumpstarter/config/client.py, jumpstarter/config/exporter.py, tests/test_listener.py
Fixes:
```
INFO:jumpstarter.exporter.exporter:Exporter: connection interrupted, reconnecting after 5 seconds: (<AioRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a0c:5a81:5301:2100:59a2:f212:8474:22e1%5D:443: connect: Network is unreachable (101)"
debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-10-23T07:31:53.753621252+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a0c:5a81:5301:2100:59a2:f212:8474:22e1%5D:443: connect: Network is unreachable (101)"}"```
```
When a DNS entry returns multiple addresses, but one of the addresses is not reachable we need to try the next...
=> Set grpc.lb_policy_name to round_robin in all grpc channels

.devfile/Containerfile.client
This seems to make writing from the devspace 'user' possible into ~/.config/jumpstarter.
=> Use the same uid/gid combination as for /home/user

.devfile.yaml
Otherwise, the automatic exposure of the route for docs doesn't work.
=> Remove http-docs, otherwise dynamic discovery fails to share route

docs/source/installation/service-cli.md, docs/source/installation/service/kind-helm.md, docs/source/installation/service/minikube-helm.md
- Fix incorrect URL for installing Service CLI
- Fix instructions to use `sudo install` instead of downloading binary into `/usr/local/bin`
- FIx issues with kind and minikube install docs, tested minikube docs to ensure that it works
=> Fix Service install docs

.devfile/Containerfile.client
This fixes various issues with devspaces:
* Installing additional pip packages on runtime
* Fixing python `jedi` codeserver error: Permission denied: '/home/user/.cache/jedi'
=> Fix /home/user/.* access in devspaces

docs/source/config.md
- Change the driver module path
- Use `url` instead of `port`
=> update doc for pyserial

docs/source/cli/clients.md, docs/source/cli/exporters.md, jumpstarter/common/grpc.py, jumpstarter/config/client.py, jumpstarter/config/exporter.py, jumpstarter/config/exporter_test.py, tests/test_client_config.py
=> TLS configuration support in config files

contrib/drivers/raspberrypi/jumpstarter_driver_raspberrypi/driver.py, contrib/drivers/raspberrypi/jumpstarter_driver_raspberrypi/driver_test.py
It seems that in gpiozero, initializing an OutputDevice changes its state.
This PR changes the driver implementation to initialize the device as an input device to validate it (for example, the pin number exists). Then, upon usage, it would initialize it as an OutputDevice and perform the operation.
Starting an exporter with an invalid pin number:
```yaml
gpio:
type: jumpstarter_driver_raspberrypi.driver.DigitalOutput
config:
pin: 70
```
```
gpiozero.exc.PinInvalidPin: 70 is not a valid pin name
```
=> raspberrypi: init device as input

jumpstarter/drivers/pyserial/client.py, jumpstarter/drivers/pyserial/console.py
Enables a cli action for pyserial device in the form of `start-console`.
```
$ jmp shell -l board abc
$$ j serial start-console
```
Fixes-Issue: #203
=> Add support for console under the j client for PySerialClient

contrib/drivers/http/src/jumpstarter_driver_http/driver.py, contrib/drivers/http/src/jumpstarter_driver_http/driver_test.py
The test was using the same file created in the for the client upload functionality, thus overriding the content of the file created in the test, which would lead to test failures. Instead, the test will use a different path for the upload.
=> http: fix http driver test

jumpstarter/client/lease.py, jumpstarter/common/grpc.py, jumpstarter/common/streams.py, jumpstarter/config/client.py, jumpstarter/config/exporter.py, jumpstarter/config/exporter_test.py, jumpstarter/config/tls.py, jumpstarter/exporter/exporter.py, jumpstarter/testing/pytest.py
The patch handling tls configuration on exporter/client didn't pass down the tls configuration to the router connections, so when set to insecure, control connection would work, but router connections failed.
Related-Issue: #192
=> Handle all instances of tls credentials

jumpstarter/cli/client.py, jumpstarter/config/client.py, jumpstarter/testing/pytest.py
1) Import the right module for the env_var name
2) Only release runtime created leases, leases received via JMP_LEASE
are kept, because those must be manually released.
=> Fix JMP_LEASE handling in pytest

docs/source/api-reference/drivers/pyserial.md
It should be "jumpstarter.drivers.pyserial.driver.PySerial"
=> Fix pyserial driver type name in documentation

contrib/drivers/http/src/jumpstarter_driver_http/driver.py, contrib/drivers/http/src/jumpstarter_driver_http/driver_test.py
- simplify tests, and add a test for file retrieval
- remove unused loop param
- call shutdown before cleanup, as docs require
=> http: simplify test and fix minor issues

docs/source/getting-started/configuration/authentication.md, docs/source/getting-started/usage/setup-distributed-mode.md, packages/jumpstarter-cli-admin/jumpstarter_cli_admin/create.py, packages/jumpstarter-cli-admin/jumpstarter_cli_admin/create_test.py, packages/jumpstarter-cli-common/jumpstarter_cli_common/opt.py
(cherry picked from commit 5d3ba48651a064619f4a24b7c3164133ed8f1611)
https://github.com/jumpstarter-dev/jumpstarter/pull/471
=> [Backport release-0.6] Update labels option syntax on admin cli to match other places
